### ISSUE TITLE
Generating PDF's after clear cache throws a server error

### ISSUE THREAD

**Issue by ammannbe** [amici-infotech/craft-super-pdf#13]
When I clear the Super PDF cache and try to generate a PDF, the site throws a server error.
I've found out, that the cache deletes the folder `storage/suepr-pdf/cache` but the DomPDF library relies on this folder.

I always have to create this folder manually.

I'm not sure where the `cache` folder does exactly come from. But maybe we should check if the folder exists and create it here:
https://github.com/amici-infotech/craft-super-pdf/blob/d5988071123289f042bff897bae62fe2c412a5fb/src/libraries/General.php#L34-L42

**Comment by ammannbe** [comment]
Hi @amici-infotech, thank you for this very fast response :)

This is my output (user and group are correct, they are given from the webhosting panel).

```bash
-bash-4.2$ pwd
/var/www/vhosts/example.ch/httpdocs/storage
-bash-4.2$ ls -lah
total 24K
drwxr-xr-x  8 example.y6bz9uupz5g psacln   128 Mar  7 15:36 .
drwxr-x---  8 example.y6bz9uupz5g psaserv  301 Mar  9 09:32 ..
drwxrwxr-x  2 example.y6bz9uupz5g psacln  4.0K Mar  9 09:53 backups
drwxr-xr-x  2 example.y6bz9uupz5g psacln  4.0K Mar  9 09:53 composer-backups
drwxr-xr-x  2 example.y6bz9uupz5g psacln  4.0K Mar  9 10:00 config-deltas
-rw-r--r--  1 example.y6bz9uupz5g psacln    53 Mar 25  2021 .gitignore
drwxr-xr-x  2 example.y6bz9uupz5g psacln  4.0K Mar  9 09:51 logs
drwxr-xr-x 13 example.y6bz9uupz5g psacln   189 Dec  9  2021 runtime
drwxrwxr-x  3 example.y6bz9uupz5g psacln    40 Mar  9 10:35 super-pdf
```

```bash
-bash-4.2$ pwd
/var/www/vhosts/example.com/httpdocs/storage/super-pdf
-bash-4.2$ ls -lah
total 1.8M
drwxrwxr-x 3 example.y6bz9uupz5g psacln   40 Mar  9 10:35 .
drwxr-xr-x 8 example.y6bz9uupz5g psacln  128 Mar  7 15:36 ..
drwxr-xr-x 2 example.y6bz9uupz5g psacln 4.0K Mar  9 10:36 cache
-rw-r--r-- 1 example.y6bz9uupz5g psacln 1.8M Mar  9 10:35 Weinkarte.pdf
```

This is the error I receive (sorry for the bad formatting):

```bash
2023-03-09 09:50:52 [web.ERROR] [yii\base\ErrorException:2] fopen(/var/www/vhosts/example.com/httpdocs/config/../storage/super-pdf/cache/gotham_normal_3a9d0a1b60318fcf483bca29311b0bb1.ufm): Failed to open stream: No such file or directory {"trace":["#0 /var/www/vhosts/example.com/httpdocs/vendor/craftcms/cms/src/web/ErrorHandler.php(79): yii\\base\\ErrorHandler->handleError(2, 'fopen(/var/www/...', '/var/www/vhosts...', 45)","#1 [internal function]: craft\\web\\ErrorHandler->handleError(2, 'fopen(/var/www/...', '/var/www/vhosts...', 45)","#2 /var/www/vhosts/example.com/httpdocs/vendor/phenx/php-font-lib/src/FontLib/AdobeFontMetrics.php(45): fopen('/var/www/vhosts...', 'w+')","#3 /var/www/vhosts/example.com/httpdocs/vendor/phenx/php-font-lib/src/FontLib/TrueType/File.php(361): FontLib\\AdobeFontMetrics->write('/var/www/vhosts...', NULL)","#4 /var/www/vhosts/example.com/httpdocs/vendor/dompdf/dompdf/src/FontMetrics.php(243): FontLib\\TrueType\\File->saveAdobeFontMetrics('/var/www/vhosts...')","#5 /var/www/vhosts/example.com/httpdocs/vendor/dompdf/dompdf/src/Css/Stylesheet.php(1475): Dompdf\\FontMetrics->registerFont(Array, 'https://example...', Resource id #884)","#6 /var/www/vhosts/example.com/httpdocs/vendor/dompdf/dompdf/src/Css/Stylesheet.php(1332): Dompdf\\Css\\Stylesheet->_parse_font_face('font-family: 'G...')","#7 /var/www/vhosts/example.com/httpdocs/vendor/dompdf/dompdf/src/Css/Stylesheet.php(299): Dompdf\\Css\\Stylesheet->_parse_css('/* GENERAL */\\n@...')","#8 /var/www/vhosts/example.com/httpdocs/vendor/dompdf/dompdf/src/Dompdf.php(615): Dompdf\\Css\\Stylesheet->load_css('\\n        /* GEN...', 3)","#9 /var/www/vhosts/example.com/httpdocs/vendor/dompdf/dompdf/src/Dompdf.php(693): Dompdf\\Dompdf->processHtml()","#10 /var/www/vhosts/example.com/httpdocs/vendor/amici/craft-super-pdf/src/libraries/Pdf.php(105): Dompdf\\Dompdf->render()","#11 /var/www/vhosts/example.com/httpdocs/vendor/amici/craft-super-pdf/src/libraries/Pdf.php(67): amici\\SuperPdf\\libraries\\Pdf->_generate()","#12 /var/www/vhosts/example.com/httpdocs/vendor/amici/craft-super-pdf/src/variables/SuperPdfVariables.php(31): amici\\SuperPdf\\libraries\\Pdf->template('partials/weinve...', Array, Array)","#13 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Extension/CoreExtension.php(1607): amici\\SuperPdf\\variables\\SuperPdfVariables->template('partials/weinve...', Array, Array)","#14 /var/www/vhosts/example.com/httpdocs/vendor/craftcms/cms/src/helpers/Template.php(146): twig_get_attribute(Object(craft\\web\\twig\\Environment), Object(Twig\\Source), Object(amici\\SuperPdf\\variables\\SuperPdfVariables), 'template', Array, 'method', false, false)","#15 /var/www/vhosts/example.com/httpdocs/storage/runtime/compiled_templates/b9/b95538e5f0bd5f3756279bb33ff0f1b7.php(1623): craft\\helpers\\Template::attribute(Object(craft\\web\\twig\\Environment), Object(Twig\\Source), Object(amici\\SuperPdf\\variables\\SuperPdfVariables), 'template', Array, 'method')","#16 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(394): __TwigTemplate_5adce336f88dff5e3e51865d55242e3b->doDisplay(Array, Array)","#17 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(367): Twig\\Template->displayWithErrorHandling(Array, Array)","#18 /var/www/vhosts/example.com/httpdocs/storage/runtime/compiled_templates/03/033b726a2cf2dce591b703ee1c278693.php(296): Twig\\Template->display(Array)","#19 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(394): __TwigTemplate_53e50246ff795f2a3b7f801e46c20810->doDisplay(Array, Array)","#20 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(367): Twig\\Template->displayWithErrorHandling(Array, Array)","#21 /var/www/vhosts/example.com/httpdocs/storage/runtime/compiled_templates/60/60cd03fac5db5c7c1a0752cfa86aebaf.php(441): Twig\\Template->display(Array)","#22 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(171): __TwigTemplate_191b786fc0e96d1fbe33d5285bbc55c7->block_content(Array, Array)","#23 /var/www/vhosts/example.com/httpdocs/storage/runtime/compiled_templates/ba/ba7fce931fda491a1ab16a5d13b80081.php(179): Twig\\Template->displayBlock('content', Array, Array)","#24 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(394): __TwigTemplate_f6d8118161914735540ff13ab93240a4->doDisplay(Array, Array)","#25 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(367): Twig\\Template->displayWithErrorHandling(Array, Array)","#26 /var/www/vhosts/example.com/httpdocs/storage/runtime/compiled_templates/60/60cd03fac5db5c7c1a0752cfa86aebaf.php(56): Twig\\Template->display(Array, Array)","#27 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(394): __TwigTemplate_191b786fc0e96d1fbe33d5285bbc55c7->doDisplay(Array, Array)","#28 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(367): Twig\\Template->displayWithErrorHandling(Array, Array)","#29 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(379): Twig\\Template->display(Array)","#30 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\\Template->render(Array, Array)","#31 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Environment.php(277): Twig\\TemplateWrapper->render(Array)","#32 /var/www/vhosts/example.com/httpdocs/vendor/craftcms/cms/src/web/View.php(451): Twig\\Environment->render('', Array)","#33 /var/www/vhosts/example.com/httpdocs/vendor/craftcms/cms/src/web/View.php(504): craft\\web\\View->renderTemplate('', Array)","#34 /var/www/vhosts/example.com/httpdocs/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(56): craft\\web\\View->renderPageTemplate('', Array, 'site')","#35 /var/www/vhosts/example.com/httpdocs/vendor/yiisoft/yii2/web/Response.php(1098): craft\\web\\TemplateResponseFormatter->format(Object(craft\\web\\Response))","#36 /var/www/vhosts/example.com/httpdocs/vendor/craftcms/cms/src/web/Response.php(286): yii\\web\\Response->prepare()","#37 /var/www/vhosts/example.com/httpdocs/vendor/yiisoft/yii2/web/Response.php(339): craft\\web\\Response->prepare()","#38 /var/www/vhosts/example.com/httpdocs/vendor/yiisoft/yii2/base/Application.php(390): yii\\web\\Response->send()","#39 /var/www/vhosts/example.com/httpdocs/web/index.php(12): yii\\base\\Application->run()","#40 {main}"],"memory":8148960,"exception":"[object] (yii\\base\\ErrorException(code: 2): fopen(/var/www/vhosts/example.com/httpdocs/config/../storage/super-pdf/cache/gotham_normal_3a9d0a1b60318fcf483bca29311b0bb1.ufm): Failed to open stream: No such file or directory at /var/www/vhosts/example.com/httpdocs/vendor/phenx/php-font-lib/src/FontLib/AdobeFontMetrics.php:45)"}
```

Thank you for your help!

**Comment by amici-infotech** [comment]
Thanks for more info. Looking at your error, it seems like you are setting a font path to cache folder that gets deleted after removing cache. You either setting it that path where super pdf code is written in twig file or in `config/super-pdf.php`

I also notice a bug with Super PDF where you set a sub folder, it should delete sub folder on clear cache, instead it was removing parent folder. I have just pushed a upgrade. I suggest you to:

- Upgrade addon to latest.
- Add PDF sub folder. (like `cache` or `pdf` or whatever you want so clearing cache will only clear that folder)
- Change font folder from `cache` to something else. like `fonts` maybe. and create fonts folder inside *storage/super-pdf/* so it reads `storage/super-pdf/fonts/` that way, clearing super pdf cache will not remove fonts folder and your issue will be fixed.

Let me know if it not works or you need more explaination on this.
